
#ifndef _NetworkPackets_H_
#define _NetworkPackets_H_

#include "NetworkPackets.pb.h"

enum SToCPacketType {
	STOC_PACKET_TYPE_GAME_STATE_BROADCAST = 0,
	STOC_PACKET_TYPE_PLAYER_IDENTIFICATION,
	STOC_PACKET_TYPE_PLAYER_POSITION_BROADCAST,
	STOC_PACKET_TYPE_PLAYER_CHANGED_LIFE_BROADCAST,
	STOC_PACKET_TYPE_PLAYER_CHANGED_SHIELD_CHARGE_BROADCAST,
	STOC_PACKET_TYPE_DISK_STATUS_BROADCAST,
	STOC_PACKET_TYPE_DISK_THROW_BROADCAST,
	STOC_PACKET_TYPE_DISK_POSITION_BROADCAST
};

enum CToSPacketType {
	CTOS_PACKET_TYPE_START_GAME_REQUEST = 0,
	CTOS_PACKET_TYPE_PLAYER_POSITION_INFORMATION,
	CTOS_PACKET_TYPE_PLAYER_THROW_INFORMATION
};

#endif